name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Verion'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          ./scripts/build-docker.sh ${{ github.event.inputs.version }}

      - name: Push Docker image to GHCR
        run: |
          ./scripts/publish-docker.sh ${{ github.event.inputs.version }}
