name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Verion'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Docker image
        run: |
          cd scripts && ./build-docker.sh ${{ github.event.inputs.version }}

      - name: Push Docker image to GHCR
        run: |
          cd scripts && ./publish-docker.sh ${{ github.event.inputs.version }}

      - name: Publish docker image
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/Dobrasync/api/packages/container/dobrasync-api/versions/${{ github.event.inputs.version }}" \
            -d '{"visibility":"public"}'
